#!/usr/bin/env bash

set -euo pipefail

./gradlew clean initLicenseList -Poverwrite=true --rerun-tasks

if ! [[ -z "$(git diff --name-only -- app)" ]]; then
    echo "diff has been generated. assemble logic might be changed and it would be a breaking change."
    exit 1
fi

echo "PASSED!"

git checkout -- app