#!/usr/bin/env bash

set -euo pipefail

run() {
  local -r category="$1"

  cp -f fixtures/$category/{artifact-definition.yml,license-catalog.yml,.artifactignore} app/license-list/

  ./gradlew clean mergeLicenseList --rerun-tasks

  if ! diff app/license-list/artifact-definition.yml fixtures/$category/expected-artifact-definition.yml; then
      echo "diff is available in fixtures/$category/artifact-definition."
      exit 1
  fi

  if ! diff app/license-list/license-catalog.yml fixtures/$category/expected-license-catalog.yml; then
      echo "diff is available in fixtures/$category/license-catalog."
      exit 1
  fi
}

run "merge"


echo "PASSED!"

git checkout -- app