#!/usr/bin/env bash

set -euo pipefail

./gradlew clean validateLicenseList --rerun-tasks

if ! [[ -z "$(git diff --name-only -- app)" ]]; then
    echo "diff has been generated. validate logic must not generate any diff."
    exit 1
fi

cp -f fixtures/validate-artifact-definition.yml app/license-list/artifact-definition.yml
cp -f fixtures/validate-license-catalog.yml app/license-list/license-catalog.yml

if ! ./gradlew clean validateLicenseList --rerun-tasks; then
    echo "validateLicenseList should have not failed"
    exit 1
fi

cp -f fixtures/validate-missing-artifact-definition.yml app/license-list/artifact-definition.yml

if ./gradlew clean validateLicenseList --rerun-tasks; then
    echo "validateLicenseList should have failed but suceeded"
    exit 1
fi


echo "PASSED!"

git checkout -- app